# Generated by Django 5.2.2 on 2025-07-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size_in_inches', models.FloatField()),
                ('resolution', models.CharField(max_length=50)),
                ('refresh_rate', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(default='images/1.jpeg', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(default='images/1.jpeg', upload_to='images/'),
        ),
    ]
