# Generated by Django 5.2.2 on 2025-07-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_monitor_alter_pc_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingChair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=20)),
                ('adjustable', models.CharField(max_length=3)),
                ('max_weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='gaming_chairs/')),
            ],
        ),
        migrations.CreateModel(
            name='Headset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_type', models.CharField(max_length=20)),
                ('has_microphone', models.CharField(max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='headsets/')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dpi', models.IntegerField()),
                ('connection_type', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='mice/')),
            ],
        ),
        migrations.AlterField(
            model_name='monitor',
            name='image',
            field=models.ImageField(default='images/1.jpeg', upload_to='monitor/'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(default='images/1.jpeg', upload_to='pc/'),
        ),
    ]
