# Generated by Django 5.2.2 on 2025-07-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_gamingchair_headset_mouse_alter_monitor_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GamingChair',
            new_name='Chair',
        ),
    ]
