# Generated by Django 5.2.2 on 2025-07-22 05:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_keyboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chair_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.chair')),
            ],
        ),
        migrations.CreateModel(
            name='Headset_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('headset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.headset')),
            ],
        ),
        migrations.CreateModel(
            name='Keyboard_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('keyboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.keyboard')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.monitor')),
            ],
        ),
        migrations.CreateModel(
            name='Mouse_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('mouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.mouse')),
            ],
        ),
        migrations.CreateModel(
            name='PC_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('pc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.pc')),
            ],
        ),
    ]
