# Generated by Django 5.2.2 on 2025-07-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_chair_comment_headset_comment_keyboard_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='category',
            field=models.CharField(default='Chair', max_length=50),
        ),
        migrations.AddField(
            model_name='headset',
            name='category',
            field=models.CharField(default='Headset', max_length=50),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='category',
            field=models.CharField(default='Keyboard', max_length=50),
        ),
        migrations.AddField(
            model_name='mouse',
            name='category',
            field=models.CharField(default='Mouse', max_length=50),
        ),
        migrations.AddField(
            model_name='pc',
            name='category',
            field=models.CharField(default='PC', max_length=50),
        ),
    ]
