# Generated by Django 5.2.2 on 2025-07-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_chair_category_headset_category_keyboard_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='category',
            field=models.CharField(default='Monitor', max_length=50),
        ),
    ]
