# Generated by Django 5.2.2 on 2025-07-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_chair_comment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='headset',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='keyboard',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='monitor',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='mouse',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pc',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
