# Generated by Django 5.2.2 on 2025-07-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_chair_stock_headset_stock_keyboard_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='image',
            field=models.ImageField(upload_to='monitor/'),
        ),
        migrations.AlterField(
            model_name='pc',
            name='image',
            field=models.ImageField(upload_to='pc/'),
        ),
    ]
